### ISSUE TITLE
Create media object (file on server) lists only 2 files

### ISSUE THREAD

**Issue by hunterdrayman** [webtrees/webtrees.github.io#120]
2.1.18 in docker on Ubuntu 22.04

I'm trying to create a multi-file media object comprising 5 files (a wedding) previously uploaded to the server as single media file objects.  In all there are 54 files in the /var/www/webtrees/data/media.

In the _**Create a media object**_ dialogue I select _**A file on the server**_ and I'm expecting that I will then be able to type in the server filename. Instead I get a drop-down list of only 2 files in that dir. There is no opportunity to type in a filename.

File permissions on the server are consistent.

**Comment by fisharebest** [comment]
This project (webtrees/webtrees.github.io) is for the project website at https://webtrees.net

For support and questions, please use the forum at https://www.webtrees.net
To report bugs, please use https://github.com/fisharebest/webtrees

From the information you give, the sofware could be working as designed.  You have 54 files in the media folder.  Only 2 are shown when you create a new media object.  Perhaps the other 52 are already assigned to media objects?

**Comment by hunterdrayman** [comment]
Thanks. My (incorrect) assumption was that a file could be associated with many media objects (and in turn with many individuals and families). Support URLs noted.
