### ISSUE TITLE
Bug report: Notes associated with a related person not showing

### ISSUE THREAD

**Issue by SchoutenCC** [webtrees/webtrees.github.io#13]
When adding a related person to for instance a PROP tag, a note can be added but the person’s page does not show this note.

Sample GEDCOM:
`1 PROP Schoorl D 1251
2 DATE FROM ABT 1955 TO ABT 1961
2 PLAC Schoorl, Noord-Holland, Nederland
2 ADDR Postweg 2
2 SOUR @S277@
3 DATA
4 TEXT Legger SCH01 art.3038
2 _ASSO @I5@
3 RELA buyer
3 NOTE Verenigd met D695`

**Comment by fisharebest** [comment]
Moved to https://github.com/fisharebest/webtrees/issues/3074
