### ISSUE TITLE
Add FAQ: What version(s) / flavor(s) of the GEDCOM standard does webtrees use and support?

### ISSUE THREAD

**Issue by nztvar** [webtrees/webtrees.github.io#138]
The currently used GEDCOM version is not easily discovered. (I did not even find webtrees.net/gedcom via search engines.)

Proposed solution: add an FAQ file: gedv.md:

[gedv.md](https://github.com/webtrees/webtrees.github.io/files/14337392/gedv.md)

**Comment by hartenthaler** [comment]
webtrees supports GEDCOM 5.5.1 and many dialects. In some parts, GEDCOM 7.0 is supported, too (there is for example a custom module that exports GEDCOM 7.0 and you can import GEDCOM 7 files (but not zipped files, not all 7.0 tags are handled already).
You can find a detailed description at https://wiki.genealogy.net/Webtrees_Handbuch/Allgemeine_Erl%C3%A4uterung_des_Programms#GEDCOM-Standards_und_webtrees

There is a short information in wikipedia: https://en.wikipedia.org/wiki/Webtrees or https://de.wikipedia.org/wiki/Webtrees

**Comment by arbor95** [comment]
closed with Commit 2f4320f
