### ISSUE TITLE
Review the dates and details of the GEDCOM info page

### ISSUE THREAD

**Issue by fisharebest** [webtrees/webtrees.github.io#34]

**Comment by nztvar** [comment]
It may be useful to state the currently supported version(s) of GEDCOM in the FAQ.

**Comment by fisharebest** [comment]
I guess this depends what you mean by "supported".

Unlike most (all?) other applications, GEDCOM isn't an import/export format.  It's our native data storage format.

We can read pretty much any dialect/version of GEDCOM and edit/display it.

That said, the user interface "encourages" (but does force) you to create data in GEDCOM 5.5.1 format.

If there's a GEDCOM structure (from either 5.5 or 7.0) that isn't displayed correctly, then that's probably a bug.

**Comment by fisharebest** [comment]
This issue was written about this page - https://webtrees.net/gedcom

It's been reviewed, but I forgot to close the issue.  I'll do that now.

If you want to continue the discussion about your other point, I'd be happy to do so.  Maybe create a separate issue for it.

(Trying to discuss multiple topics in a single issue gets confusing.)
