### ISSUE TITLE
Custom template

### ISSUE THREAD

**Issue by jchue** [webtrees/webtrees.github.io#5]
@fisharebest Here is my proposal for the new template design. (Take the spacing and sizing with a grain of salt, as it is not pixel-perfect.) I tried to pick a font face that captures the gist of the webtrees logo. If you are ok with this, I will probably start with the one-column layout, since even documentation pages can utilize it in the interim. The homepage and a few other components still require design, but this should cover most use cases.

**Documentation Page:**
![design_documentation-page](https://user-images.githubusercontent.com/5141427/71117349-d589c200-218a-11ea-844c-00d45a8bca19.png)

**One-Column Page:**
![design_one-column-page](https://user-images.githubusercontent.com/5141427/71117359-d884b280-218a-11ea-8c4a-d8bb8b5884fe.png)

**Comment by jchue** [comment]
And here's the home (still experimenting with button colors):
![design_home](https://user-images.githubusercontent.com/5141427/71218418-4063f780-2276-11ea-9b77-93e788c4ef25.png)

**Comment by fisharebest** [comment]
Very nice.

Much better than anything I could design!
