### ISSUE TITLE
modules.md/list of modules: categorization 

### ISSUE THREAD

**Issue by ungeahnt** [webtrees/webtrees.github.io#98]
What do you think about making the [list of modules (modules.md)](https://github.com/webtrees/webtrees.github.io/blob/main/download/modules.md)  a bit clearer?

For example, it is possible to create a drop-down menu with categories:

```
<details>
<summary>title</summary>
text
</details>
```

I could make the change. Suggestions for the respective category names would be welcome at any time.
It could look like this:

## Sorted by categories
<details>
<summary>Charts</summary>
<br>
 
----------

### Ancestor Fan Chart - by MagicSunday - `1.7` - `2.0` - `2.1` - [website](https://github.com/magicsunday/webtrees-fan-chart)

A replacement for the webtrees fan chart, this module uses the D3JS library to provide
an attractive, animated fan chart.

----------

### Pedigree Chart - by MagicSunday - `2.0` - `2.1` - [website](https://github.com/magicsunday/webtrees-pedigree-chart)

A replacement for the webtrees pedigree chart, this module uses the D3JS library to provide
an attractive pedigree chart capable to display up to 25 generations.

----------

</details>
<details>
<summary>Historical facts</summary>
<br>

----------

### GermanChancellorsAndPresidents - by Hartenthaler - `2.0` - `2.1` - [website](https://github.com/hartenthaler/german-chancellors-and-presidents)

Provides historical facts (in German language) - Chancellors and Presidents of Germany (since 1949).

----------

### GermanWarsAndBattlesWorldwide - by Hartenthaler - `2.0` - `2.1` - [website](https://github.com/hartenthaler/german-wars-and-battles-worldwide)

Provides historical facts (in German language) - Wars and Battles Worldwide (since 900).

----------

</details>

<details>
<summary>Media</summary>
<br>

 ----------

### Faces - by UksusoFF - `1.7` - `2.0` - `2.1` - [website](https://github.com/UksusoFF/webtrees-faces)

Tag faces on photos.

----------

### Gallery - by vytux - `1.7` - [website](https://github.com/vytux-com/vytux_gallery3)

Display all the photos in a folder.

----------

</details>

<details>
<summary>Themes</summary>
<br>
 
----------

### Argon Theme - by Jonathan Chue - `2.0` - `2.1` - [website](https://github.com/jchue/argon-webtrees-theme)

A theme for the webtrees based on the Argon Design System.

----------

### JustBlack Theme - by JustCarmen - `1.7` - [website](https://justcarmen.nl/modules-webtrees-1/justblack-theme) - [demo](http://www.ahnen-recherche.de/webtrees)

A dark-gray layout with orange and yellow accents. Smooth Top Navigation Menu.
Nice font for titles. Colorbox support for pdf files. Responsive dialog boxes.

_Note: As of webtrees 2.0/2.1 the JustBlack theme is part of the JustLight theme (see below)_.

 ----------
 
### JustLight Theme - by JustCarmen - `1.7` - [website](https://justcarmen.nl/modules-webtrees-1/justlight-theme) - `2.0` - `2.1` - [website](https://justcarmen.nl/modules-webtrees-2/justlight-theme) - [demo](https://wijzijnfamilie.nl)

A light theme with focus on readability. It uses a full screen where necessary but takes into account small screens too. This theme is optimized for using on tablets and mobile phones and offers different layouts with some extra's. If you like a clean layout you certainly want to try this theme.

There are two color palettes available. The JustLight palette is a modern palette in clean white and blue. The JustBlack palette has a dark background and orange accents. This palette is more relaxing for the eyes. You can set a default palette for all users or let your users make their own choice.

----------

 
</details>

<details>
<summary>...</summary>
</details>

## All modules 
<details>
<summary>All modules (in alphabetical order)</summary>
<br>
 
----------

### Ancestor Fan Chart - by MagicSunday - `1.7` - `2.0` - `2.1` - [website](https://github.com/magicsunday/webtrees-fan-chart)

A replacement for the webtrees fan chart, this module uses the D3JS library to provide
an attractive, animated fan chart.

<br>

----------

...

----------

</details>

**Comment by Bogiegit** [comment]
I would welcome this change.

**Comment by arbor95** [comment]
yes, you can do that
